import type { Metadata } from "next";
import localFont from "next/font/local";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/AppSidebar";

const poppins = Poppins({
  weight: "100",
  subsets: ["latin"],
  variable: "--poppin",
});

export const metadata: Metadata = {
  title: "Eden Home | A Place for all your Managing Needs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.variable}>{children}</body>
    </html>
  );
}
